path: data/processed/dataset_7classes
train: train/images
val: eval/images
test: test/images
names:
- CARIES
- PERIAPICAL_PATHOLOGY
- PERIODONTAL_BONE
- IMPACTED_TOOTH
- ROOT_PATHOLOGY
- TREATED_TOOTH
- DEVICE_IMPLANT
nc: 7
